CREATE TABLE Pokemons(
   id UUID PRIMARY KEY NOT NULL,
   name VARCHAR(255) UNIQUE NOT NULL,
   hp INTEGER,
   attack INTEGER,
   defense INTEGER,
   speed INTEGER,
   height INTEGER,
   weight INTEGER,
   img VARCHAR(255),
   db BOOLEAN);

CREATE TABLE types(
   id UUID PRIMARY KEY NOT NULL,
   name VARCHAR(255) UNIQUE NOT NULL);



